<?php

use mono\Core;


/**
 * english.php Sep 23, 2015
 * Copyright (c) 2015 Venom Services
 *
 * LICENSE:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @author VenomServices <contact@venomservices.com>
 * @copyright 2015 VenomServices
 * @license https://opensource.org/licenses/MIT
 * @link https://venomservices.com
 */
return [
    'validation' => [
        'required' => '%s is required.',
        'url' => '%s must be a valid URL.',
        'alphabet' => '%s must contain only alphabet letters.',
        'numeric' => '%s must contain only numbers.',
        'alphanumeric' => '%s must contain only alphabet letters and numbers.',
        'min-text' => '%s must be a minimum of %s characters.',
        'max-text' => '%s must be a maximum of %s characters.',
        'min-num' => '%s must be a minimum of %s.',
        'max-num' => '%s must be a maximum of %s.',
        'email' => '%s must be a valid email.',
        'password_doesnt_match' => 'The passwords you entered doesn\'t match.',
        'select' => '%s must be %s.',
        'date' => '%s must be a valid date.',
        'csrftoken_doesnt_match' => "The csrf token provided doesn't match the token generated by the server."
    ],
    'log' => [
        'plugin_enable' => "Enabling plugin %s v%s - %s",
        'plugin_disable' => "Disabling plugin %s v%s",
        'loaded_controller' => "The controller \"%s\" was loaded using the method \"%s\" with arguments: %s",
        'csrfToken_generated' => "CSRF token generated. Token value: \"%s\"",
        'csrfToken_verified' => "CSRF token verification passed. Token value: \"%s\"",
        'csrfToken_unverified' => "CSRF token verification failed. Token value: \"%s\", Expected token value: \"%s\"",
        '404error' => "404 error thrown in File: \"%s\" at line: %s.",
        'loaded' => "Finished in %s second(s)."
    ],
    'errors' => [
        'config_error_0' => "The config file \"%s\" was not found.",
        'config_error_1' => "The requested configuration path \"%s\" is not a String.",
        'config_error_2' => "The requested configuration path \"%s\" is not an Integer.",
        'config_error_3' => "The requested configuration path \"%s\" is not a Boolean.",
        'config_error_4' => "The requested configuration path \"%s\" is not an Array.",
        'database_error_0' => "Tried to use the database while it's disabled. File: \"%s\". Line: %s",
        'database_error_1' => "Database type unidentified. Please use one of the following: %s",
        'database_error_2' => "Expecting the %s parameter passed to \"%s\" to have at least \"%s\".",
        'database_error_3' => "Expecting to have at least one column when creating the table \"%s\".",
        'controller_exists' => "The controller \"%s\" already exists.",
        'plugins_dir_notfound' => "The plugins directory was not found. No plugins will be loaded.",
        'controller_error_0' => "The controller \"%s\" was not found in the directory: \"%s\"",
        'controller_error_1' => "The controller \"%s\" class was not found in the PHP file \"%s\".",
        'controller_error_2' => "The controller \"%s\" was not loaded or found in the controllers directory.",
        'controller_error_3' => "The controller \"%s\" must extend mono\\models\\Controller.",
        'controller_error_4' => "The method \"%s\" was not found in the controller \"%s\". Reverting to the default method \"index\".",
        'controller_error_5' => "The view file \"%s\" was not found for the controller \"%s\".",
        'controller_error_6' => "There were no default controllers loaded by the application configuration. If the page is blank, this may be the reason.",
        'plugin_error_0' => "The plugin.json was not found for the plugin \"%s\".",
        'plugin_error_1' => "The plugin.json for the plugin \"%s\" is invalid.",
        'plugin_error_2' => "The plugin name \"%s\" is already in use. File: \"%s\".",
        'plugin_error_3' => "The main class \"%s\" for the plugin \"%s\" was not found.",
        'plugin_error_4' => "The main class \"%s\" for the plugin \"%s\" must extend mono\\models\\Plugin.",
        'plugin_error_5' => "The plugin \"%s\" was already enabled.",
        'plugin_error_6' => "The plugin \"%s\" was never enabled.",
        'plugin_error_7' => "The plugin \"%s\" requires a version of PHP that is higher than v%s, disabling.",
        'plugin_error_8' => "The plugin \"%s\" requires a version of PHP that is lower than v%s, disabling.",
        'plugin_error_9' => "The plugin \"%s\" requires a version of PHP that is equal to v%s, disabling.",
        'plugin_error_10' => "The plugin \"%s\" requires a version of the plugin \"%s\" that is higher than v%s, disabling.",
        'plugin_error_11' => "The plugin \"%s\" requires a version of the plugin \"%s\" that is lower than v%s, disabling.",
        'plugin_error_12' => "The plugin \"%s\" requires a version of the plugin \"%s\" that is equal to v%s, disabling.",
        'plugin_error_13' => "The plugin \"%s\" dependency \"%s\" was not found, disabling.",
        'plugin_error_14' => "The plugin \"%s\" tried to load the plugin \"%s\" first but it was not found.",
        'plugin_error_15' => "File: \"%s\" at line: %s tried to enable the plugins. Only Core can enable plugins.",
        'plugin_error_16' => "The plugin \"%s\" requires a version of the plugin \"%s\" that is higher than or equal to v%s, disabling.",
        'plugin_error_17' => "The plugin \"%s\" requires a version of the plugin \"%s\" that is lower than or equal to v%s, disabling.",
        'plugin_error_18' => "The plugin \"%s\" requires a version of PHP that is higher than or equal to v%s, disabling.",
        'plugin_error_19' => "The plugin \"%s\" requires a version of PHP that is lower than or equal to v%s, disabling.",
        'plugin_error_20' => "The plugin \"%s\" depends on the plugin \"%s\" but it was disabled, cannot enable plugin.",
        'custom_regex' => "Custom regex for validator ignored because no regex was supplied. File: \"%s\" at line: %s.",
    ]
];